# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild_npm_node]
steps:
  - name: working_dir
    entrypoint: cd
    args: ["apps/api"]
  # Install dependencies
  - name: install
    entrypoint: bun
    args: ["install"]
  # Run tests
  - name: tests
    entrypoint: bun
    args: ["test"]
  # Run custom commands
  - name: build
    entrypoint: bun
    args: ["run", "build"]
# [END cloudbuild_npm_node]
options:
  logging: CLOUD_LOGGING_ONLY