steps:
  # Install dependencies
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
    id: 'deps-install'
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      whoami
      apt-get update
      apt-get install node
      ./node_modules/.bin/nx test api
    waitFor: ['deps-install']
  # Docker Build
  - name: 'docker'
    args: ['build', '-t', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA', '.']
  # Docker Push
  - name: 'docker'
    args: ['push', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA']
  # Update gcloud
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - components
      - update
    entrypoint: gcloud
  # Check version
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - --version
    entrypoint: gcloud
  # Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
    entrypoint: gcloud
timeout: 600s
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY